source 'http://rubygems.org'

gem 'ancestry'
gem 'bcrypt-ruby', :require => 'bcrypt'
gem 'cancan'
gem 'carrierwave'
gem 'compass'
gem 'haml'
gem 'jquery-rails'
gem 'mini_magick'
gem 'rails', '3.0.9'
gem 'rake'
gem 'rdoc'
gem 'sanitize'
gem 'sass'
gem 'sqlite3'